[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "client-server-backend"
version = "1.0.0"
dependencies = [
    "fastapi==0.104.1",
    "uvicorn==0.24.0", 
    "python-multipart==0.0.6",
    "python-dotenv==1.0.0"
]